import { BARBERS,SERVICES,today,addDays,minutes,timeLabel } from './model.js';
import { getBookings,createBooking,updateBooking } from './store.js';
import { t,esc,prettyDate } from './i18n.js';
import { toast,syncModalState } from './ui.js';
const root=document.getElementById('desk-view');
const dialog=document.getElementById('appointment-dialog');
const dialogContent=document.getElementById('appointment-content');
const state={date:today(),view:window.innerWidth<650?'list':'day',barber:'all'};
const statusKey=status=>status==='done'?'doneStatus':status;
let current=null;
export function renderDesk(){
  const all=getBookings();
  const bookings=all.filter(b=>b.date===state.date&&(state.barber==='all'||b.barber===state.barber)).sort((a,b)=>a.time.localeCompare(b.time));
  const active=bookings.filter(b=>!['cancelled','blocked'].includes(b.status));
  root.innerHTML=`<div class="desk-shell"><div class="desk-heading"><div><p class="eyebrow">BRAVOCUTS / STUDIO DESK</p><h1>${t('desk')}</h1><p>${t('deskSub')}</p></div><div class="desk-actions"><button class="button secondary" data-add-block>＋ ${t('block')}</button><button class="button dark" data-add>＋ ${t('add')}</button></div></div><div class="day-summary"><span><strong>${active.length}</strong>${t('totalDay')}</span><span><i class="status-dot"></i>${t('confirmed')} ${active.filter(b=>b.status==='confirmed').length}</span><span><i class="status-dot arrived"></i>${t('arrived')} ${active.filter(b=>b.status==='arrived').length}</span><span><i class="status-dot cutting"></i>${t('cutting')} ${active.filter(b=>b.status==='cutting').length}</span></div><div class="desk-toolbar"><div class="date-navigation"><button class="icon-button" data-prev-date aria-label="Previous day">←</button><input type="date" name="desk-date" value="${state.date}" aria-label="${t('date')}"><button class="icon-button" data-next-date aria-label="Next day">→</button><button class="button secondary small" data-today>${t('today')}</button></div><div class="desk-filters"><select name="desk-barber" aria-label="${t('stepBarber')}"><option value="all">${t('all')}</option>${BARBERS.map(b=>`<option value="${b.id}" ${b.id===state.barber?'selected':''}>${b.name}</option>`).join('')}</select><div class="view-toggle" role="group" aria-label="View"><button data-view="day" class="${state.view==='day'?'active':''}" aria-pressed="${state.view==='day'}">${t('day')}</button><button data-view="list" class="${state.view==='list'?'active':''}" aria-pressed="${state.view==='list'}">${t('list')}</button></div></div></div><p class="desk-mobile-date">${prettyDate(state.date)} · ${t('timezone')}</p>${state.view==='day'?schedule(bookings):list(bookings)}<p class="desk-note">${t('deskDemo')} · ${t('sample')}</p></div>`;
  root.querySelector('[data-add]').onclick=()=>openAppointment();root.querySelector('[data-add-block]').onclick=()=>openAppointment(null,{block:true});
  root.querySelector('[data-prev-date]').onclick=()=>{state.date=addDays(state.date,-1);renderDesk();};
  root.querySelector('[data-next-date]').onclick=()=>{state.date=addDays(state.date,1);renderDesk();};
  root.querySelector('[data-today]').onclick=()=>{state.date=today();renderDesk();};
  root.querySelector('[name=desk-date]').onchange=e=>{if(e.target.value)state.date=e.target.value;renderDesk();};
  root.querySelector('[name=desk-barber]').onchange=e=>{state.barber=e.target.value;renderDesk();};
  root.querySelectorAll('[data-view]').forEach(btn=>btn.onclick=()=>{state.view=btn.dataset.view;renderDesk();});
  root.querySelectorAll('[data-appointment]').forEach(btn=>btn.onclick=()=>openAppointment(btn.dataset.appointment));
  root.querySelectorAll('.schedule-column').forEach(column=>column.onclick=e=>{if(e.target!==column)return;const offset=Math.floor((e.clientY-column.getBoundingClientRect().top)/36)*30;openAppointment(null,{barber:column.dataset.barber,time:timeLabel(Math.min(1230,600+offset))});});
}
function schedule(bookings){
  return `<div class="schedule"><div class="schedule-headers"><div></div>${BARBERS.map(b=>`<div><img src="${b.image}" alt=""><span><strong>${b.name}</strong><small>${bookings.filter(x=>x.barber===b.id&&!['blocked','cancelled'].includes(x.status)).length} ${t('appointments')}</small></span></div>`).join('')}</div><div class="schedule-scroll"><div class="schedule-body"><div class="schedule-time">${Array.from({length:11},(_,i)=>`<span style="top:${i*72}px">${timeLabel(600+i*60)}</span>`).join('')}</div>${BARBERS.map(b=>`<div class="schedule-column" data-barber="${b.id}" aria-label="${b.name}">${bookings.filter(x=>x.barber===b.id&&x.status!=='cancelled').map(x=>`<button class="schedule-event ${x.status}" data-appointment="${x.id}" style="top:${(minutes(x.time)-600)*1.2+2}px;height:${x.duration*1.2-4}px" aria-label="${esc(x.name)} ${x.time} ${b.name} ${t(statusKey(x.status))}"><span class="event-time">${x.time}–${timeLabel(minutes(x.time)+x.duration)}</span><strong>${esc(x.status==='blocked'?t('blockedName'):x.name)}</strong>${x.duration>=45?`<span class="event-detail">${x.service==='block'?t('blocked'):t(x.service)} · ${t(statusKey(x.status))}</span>`:''}</button>`).join('')}</div>`).join('')}</div></div></div>`;
}
function list(bookings){return bookings.length?`<div class="booking-list">${bookings.map(b=>`<button class="list-row" data-appointment="${b.id}"><span>${b.time}<small>${timeLabel(minutes(b.time)+b.duration)}</small></span><span><strong>${esc(b.status==='blocked'?t('blockedName'):b.name)}</strong><small>${b.service==='block'?t('blocked'):t(b.service)} · ${BARBERS.find(x=>x.id===b.barber).name}</small></span><span class="list-barber">${BARBERS.find(x=>x.id===b.barber).name}</span><span class="status-pill ${b.status}">${t(statusKey(b.status))}</span></button>`).join('')}</div>`:`<div class="empty-state">${t('emptyDay')}</div>`;}
function defaultTime(){const now=new Date();const thai=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Bangkok',hour:'2-digit',minute:'2-digit',hour12:false}).format(now);return timeLabel(Math.max(600,Math.min(1200,Math.ceil((minutes(thai)+1)/15)*15)));}
function openAppointment(id=null,options={}){
  const existing=id?getBookings().find(b=>b.id===id):null;
  current={id,block:existing?.service==='block'||options.block===true};
  const b=existing||{name:'',phone:'',note:'',date:state.date,time:options.time||defaultTime(),barber:options.barber||(state.barber==='all'?'yu':state.barber),service:options.block?'block':'cut',duration:60,status:options.block?'blocked':'confirmed',photos:[]};
  const history=existing?getBookings().filter(x=>x.id!==id&&x.service!=='block'&&((b.phone&&x.phone===b.phone)||(!b.phone&&x.name.toLowerCase()===b.name.toLowerCase()))).sort((a,c)=>(c.date+c.time).localeCompare(a.date+a.time)):[];
  dialogContent.innerHTML=`<div class="dialog-top"><span class="dialog-brand">BRAVOCUTS</span><button class="icon-button" data-close-appointment aria-label="${t('close')}">×</button></div><div class="appointment-body"><p class="eyebrow">${t('sampleData')}</p><h2 id="appointment-title">${t(id?'editTitle':current.block?'blockTitle':'newAppointment')}</h2><form id="appointment-form"><div class="form-grid">${current.block?'':`<label class="span-2">${t('name')}<input name="name" value="${esc(b.name)}" maxlength="80" required></label><label class="span-2">${t('phone')} · ${t('optional')}<input name="phone" type="tel" value="${esc(b.phone)}" maxlength="25" placeholder="+66"></label>`}<label>${t('date')}<input name="date" type="date" value="${b.date}" required></label><label>${t('time')}<input name="time" type="time" min="10:00" max="20:30" value="${b.time}" required></label><label>${t('stepBarber')}<select name="barber">${BARBERS.map(x=>`<option value="${x.id}" ${x.id===b.barber?'selected':''}>${x.name}</option>`).join('')}</select></label>${current.block?`<label>${t('duration')}<select name="duration">${[30,60,90,120].map(n=>`<option value="${n}" ${n===b.duration?'selected':''}>${n} ${t('min')}</option>`).join('')}</select></label>`:`<label>${t('service')}<select name="service">${SERVICES.map(s=>`<option value="${s.id}" ${s.id===b.service?'selected':''}>${t(s.id)} · ${s.duration} ${t('min')}</option>`).join('')}</select></label><label class="span-2">${t('status')}<select name="status">${['confirmed','arrived','cutting','done','cancelled'].map(s=>`<option value="${s}" ${s===b.status?'selected':''}>${t(statusKey(s))}</option>`).join('')}</select></label>`}<label class="span-2">${t('notes')}<textarea name="note" maxlength="600">${esc(b.note)}</textarea></label></div><div class="photo-preview">${(b.photos||[]).map(p=>`<a href="${p.data}" target="_blank" rel="noopener" aria-label="${t('reference')}"><img class="admin-photo" src="${p.data}" alt="${esc(p.name)}"></a>`).join('')}</div><p class="error" role="alert"></p><div class="appointment-actions"><button class="button dark" type="submit">${t('save')} ✓</button>${id&&b.status!=='cancelled'?`<button class="danger-link" type="button" data-cancel-appointment>${t('cancelBooking')}</button>`:''}</div></form>${id&&!current.block?`<div class="history"><h3>${t('customerHistory')}</h3>${history.length?history.map(x=>`<p>${prettyDate(x.date)} · ${x.time} · ${t(x.service)} · ${BARBERS.find(v=>v.id===x.barber).name}</p>`).join(''):`<p>${t('historyEmpty')}</p>`}</div>`:''}<p class="desk-note">${t('deskDemo')}</p></div>`;
  dialogContent.querySelector('[data-close-appointment]').onclick=()=>dialog.close();
  dialogContent.querySelector('#appointment-form').onsubmit=e=>{e.preventDefault();saveAppointment(e.currentTarget,existing);};
  dialogContent.querySelector('[data-cancel-appointment]')?.addEventListener('click',()=>{if(confirm(t('cancelConfirm'))){updateBooking(id,{status:'cancelled'});dialog.close();toast(t('cancelledSaved'));}});
  dialog.showModal();syncModalState();
}
function saveAppointment(form,existing){
  const data=Object.fromEntries(new FormData(form));const isBlock=current.block;
  const selectedService=SERVICES.find(s=>s.id===data.service);
  const request={date:data.date,time:data.time,barber:data.barber,service:isBlock?'block':data.service,duration:isBlock?Number(data.duration):selectedService?.duration,price:isBlock?0:selectedService?.price,name:isBlock?t('blockedName'):data.name.trim(),phone:data.phone?.trim()||'',note:data.note.trim(),status:isBlock?'blocked':data.status,photos:existing?.photos||[],demo:true};
  const error=dialogContent.querySelector('.error');
  if(!request.name||!request.duration||!request.date||!request.time){error.textContent=t('saveError');return;}
  if((!existing||request.date!==existing.date||request.time!==existing.time)&&new Date(`${request.date}T${request.time}:00+07:00`)<=new Date()){error.textContent=t('datePast');return;}
  try{if(existing)updateBooking(existing.id,request);else createBooking(request);state.date=request.date;renderDesk();dialog.close();toast(t(existing?'saved':isBlock?'blockedSaved':'added'));}catch(e){error.textContent=t(e.message==='storage'?'storage':'conflict');}
}
dialog.addEventListener('close',syncModalState);
window.addEventListener('bravo:bookings',renderDesk);
window.addEventListener('storage',renderDesk);
window.addEventListener('bravo:desk-date',e=>{state.date=e.detail;renderDesk();});
window.addEventListener('bravo:language',()=>{renderDesk();if(dialog.open){dialog.close();}});
