export function buildShopHome(L){
 const hero=document.querySelector('#barbers');
 hero.outerHTML=`<section class="shop-hero" id="studio"><div class="shop-kicker"><span>BRAVOCUTS / KATHU, PHUKET</span><span>PRECISION. PEOPLE. PERSONALITY.</span></div><span class="shop-ghost" aria-hidden="true">BRAVO</span><div class="shop-front"><img src="assets/shop-front.webp" alt="${L('หน้าร้าน BRAVOCUTS พร้อมป้ายไฟสีทองและเก้าอี้ตัดผมด้านใน','BRAVOCUTS storefront with warm gold signage and barber chairs inside','BRAVOCUTS 店面，暖金色招牌与理发椅','Вход в BRAVOCUTS с золотой вывеской и креслами внутри')}" fetchpriority="high"></div><div class="shop-hero-copy"><p class="eyebrow">YOUR NEIGHBOURHOOD BARBERSHOP</p><h1>GOOD CUTS.<br><span>GREAT VIBES.</span></h1><p>${L('ร้านตัดผมชายในกะทู้ ภูเก็ต ที่ให้ความสำคัญกับทุกรายละเอียด ตั้งแต่ทรงที่คุณชอบ ไปจนถึงบรรยากาศที่ทำให้คุณอยากกลับมา','Your barbershop in Kathu, Phuket. A considered cut, a little conversation, and a place you’ll want to come back to.','普吉岛卡图的男士理发店。从您喜欢的发型，到舒适的店内氛围，每个细节都用心。','Барбершоп в Кату, Пхукет. Продуманная стрижка, приятная беседа и место, куда хочется вернуться.')}</p><a class="primary" href="booking.html">${L('เลือกช่างและจองคิว','Find your barber & book','选择理发师并预约','Выбрать мастера и записаться')}</a><a class="shop-work-link" href="#work">${L('ดูผลงานของร้าน','Explore our work','欣赏我们的作品','Посмотреть работы')} ↓</a><div class="shop-facts"><span>01 / ${L('เลือกช่าง','YOUR BARBER','选择理发师','ВАШ МАСТЕР')}</span><span>02 / ${L('เลือกเวลา','YOUR TIME','选择时间','ВАШЕ ВРЕМЯ')}</span><span>03 / ${L('สไตล์คุณ','YOUR STYLE','您的风格','ВАШ СТИЛЬ')}</span></div></div><div class="shop-hero-bottom"><span></span></div></section>`;
 const work=document.querySelector('#work');
 work.insertAdjacentHTML('beforebegin',`<section class="shop-story" id="inside"><div class="story-photo"><img src="assets/shop-interior.jpg" alt="${L('ช่างกำลังตัดผมภายในร้าน ใต้ไฟเพดานลายรังผึ้ง','A haircut in progress beneath the studio’s honeycomb lights','蜂窝灯光下，理发师正在为顾客理发','Мастер за работой под геометрическими светильниками')}" loading="lazy"><span>INSIDE BRAVOCUTS / KATHU</span></div><div class="story-copy"><p class="eyebrow">MORE THAN A HAIRCUT</p><h2>${L('พื้นที่เล็ก ๆ<br>ที่ใส่ใจทุกดีเทล','A good place.<br>A better haircut.','用心的空间，<br>精致的发型。','Своя атмосфера.<br>Ваша стрижка.')}</h2><p>${L('ไฟลายรังผึ้ง เก้าอี้ดำตัดทอง และบรรยากาศเป็นกันเอง คือส่วนหนึ่งของ BRAVOCUTS เข้ามาพร้อมไอเดียหรือรูปเรฟ แล้วคุยกับช่างเพื่อหาทรงที่เข้ากับคุณ','Honeycomb lights, black-and-gold chairs and an easygoing atmosphere. Bring an idea or a reference photo, and work with your barber to find your look.','蜂窝灯、黑金理发椅与轻松氛围。带上灵感或参考照片，和理发师一起找到适合您的造型。','Геометрический свет, чёрно-золотые кресла и непринуждённая атмосфера. Приходите с идеей или фото — подберём ваш образ вместе.')}</p><div class="story-detail"><span>01</span><div><h3>${L('คุยเรื่องทรงก่อนเริ่ม','A conversation first','先沟通，再剪发','Сначала — ваши пожелания')}</h3><p>${L('บอกความยาว ทรงที่ชอบ และวิธีที่คุณเซ็ตผมในทุกวัน','Tell us the length, shape and how you style your hair.','告诉我们您喜欢的长度、造型和日常打理方式。','Расскажите о длине, форме и привычной укладке.')}</p></div></div><div class="story-detail"><span>02</span><div><h3>${L('เลือกช่าง เลือกเวลาของคุณ','Your barber. Your time.','您的理发师，您的时间','Ваш мастер. Ваше время.')}</h3><p>${L('ดูเวลาว่างและส่งรูปเรฟได้ในหน้าจอง','Check availability and add reference photos when booking.','预约时可查看空闲时间并上传参考照片。','Выберите свободное время и добавьте фото при записи.')}</p></div></div><a class="shop-work-link" href="booking.html">${L('เริ่มจองคิว','Book your visit','开始预约','Записаться')}</a></div></section>`);
 const heading=work.querySelector('.section-top');
 heading.querySelector('h2').textContent=L('ทุกทรง มีคาแรกเตอร์','EVERY CUT. ITS OWN CHARACTER.','每款发型，都有个性','У КАЖДОЙ СТРИЖКИ СВОЙ ХАРАКТЕР.');
 const items=[
 ['assets/work-curl-fade.jpg','CURLS & CLEAN LINES',null],
 ['assets/work-3.jpg','TEXTURE / DETAIL','DdOvoDFzMS6'],
 ['assets/work-2.jpg','FROM THE CHAIR','DdVZhbGzBeW'],
 ['assets/work-4.jpg','FRESH PERSPECTIVE','DdF78I8ThQe'],
 ['assets/work-1.jpg','THE FINISHING TOUCH','Ddak93HTjBb'],
 ['assets/shop-interior.jpg','CRAFT IN PROGRESS',null]
 ];
 const cards=duplicate=>items.map(([src,label,id],i)=>{const content=`<img src="${src}" alt="${duplicate?'':L('ผลงานและบรรยากาศจริงของ BRAVOCUTS','Real BRAVOCUTS work and studio moments','BRAVOCUTS 真实作品与店内时刻','Работы и атмосфера BRAVOCUTS')+' '+(i+1)}" loading="lazy"><span class="gallery-caption"><span>${label}</span><span>0${i+1}</span></span>`;return id&&!duplicate?`<a class="loop-card" href="https://www.instagram.com/bravocuts_phuket/reel/${id}/" target="_blank" rel="noopener">${content}</a>`:`<figure class="loop-card">${content}</figure>`;}).join('');
 work.querySelector('.gallery').outerHTML=`<div class="loop-toolbar"><span>${L('ภาพจริงจากร้านและ Instagram','REAL CUTS / REAL PEOPLE','真实作品 / 真实顾客','НАСТОЯЩИЕ РАБОТЫ / ЛЮДИ')}</span></div><div class="work-loop" role="region" aria-label="${L('ผลงานร้านเลื่อนวน','Looping portfolio','循环作品集','Лента работ')}" tabindex="0"><div class="loop-track"><div class="loop-group">${cards(false)}</div><div class="loop-group" aria-hidden="true" inert>${cards(true)}</div></div></div>`;
 /* Replay the shopfront's arrival each time it scrolls back into view, so the
    page feels freshly loaded rather than frozen after the first paint. */
 const front=document.querySelector('.shop-front');
 if(front&&!matchMedia('(prefers-reduced-motion: reduce)').matches&&'IntersectionObserver' in window){
  front.classList.add('replayable');
  new IntersectionObserver(entries=>{for(const entry of entries)front.classList.toggle('is-away',!entry.isIntersecting);},{threshold:0}).observe(front);
 }
}
